version: '3.8'

services:
  vldb:
    image: mysql:8.0
    container_name: vldbc1
    environment: 
      MYSQL_ROOT_PASSWORD: example 
      MYSQL_DATABASE: testdb
  vlflaskwebapp:
    image: vlflaskwebapp1
    build: .
    ports:
      - "3019:5000"
    environment:
      FLASK_ENV: development
      MYSQL_HOST: vldb
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: testdb
    depends_on:
      - vldb
